import {
  Target,
  Dumbbell,
  BarChart3,
  Heart,
  Book,
  Coffee,
  Zap,
  Moon,
  Sun,
  Droplet,
  Activity,
  TrendingUp,
  Award,
  CheckCircle,
  Circle,
  Briefcase,
  Home,
  Users,
  Star,
  Flag,
  Brain,
  Leaf,
  Edit,
  Trash2,
} from 'lucide-react';

const _ICON_MAP: Record<string, any> = {
  '🎯': Target,
  '💪': Dumbbell,
  '📊': BarChart3,
  '❤️': Heart,
  '📚': Book,
  '☕': Coffee,
  '⚡': Zap,
  '🌙': Moon,
  '☀️': Sun,
  '💧': Droplet,
  '📈': Activity,
  '📉': TrendingUp,
  '🏆': Award,
  '✅': CheckCircle,
  '💼': Briefcase,
  '🏠': Home,
  '👥': Users,
  '⭐': Star,
  '🚩': Flag,
  // Habit-specific icons
  'activity': Activity,
  'heart': Heart,
  'book': Book,
  'droplet': Droplet,
  'brain': Brain,
  'sun': Sun,
  'moon': Moon,
  'zap': Zap,
  'target': Target,
  'coffee': Coffee,
  'star': Star,
  'leaf': Leaf,
  'edit': Edit,
  'trash': Trash2,
};

export const getLucideIcon = (emoji: string) => {
  return _ICON_MAP[emoji] || Circle;
};
